config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :delete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save :downcase_email

  # Username validations
  VALID_USERNAME_REGEX = /\A\w+\z/i
  validates :username, presence: true,
                       length: { in: 3..50 },
                       format: { with: VALID_USERNAME_REGEX },
                       uniqueness: true


  # Email validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.([a-z\d\-]+\.)*[a-z]{2,}\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # Password validations
  validates :password, presence: true,
                       length: { minimum: 6 },
                       allow_nil: true

has_secure_password

  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # display log in form
  end

  def create
    user = User.find_by_username(params[:user])
    user ||= User.find_by_email(params[:user])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have been succesfully logged in."
      redirect_to user
    else
      flash.now[:error] = "Invalid username or email/password combination!"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You have been succesfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorized_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Profile created succesfully!"
      redirect_to @user
    else
      flash.now[:error] = "We had a problem to process submited form!"
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated succesfully!"
      redirect_to @user
    else
      flash.now[:error] = "We had a problem to process submited form!"
      render 'edit'
    end

  end

  def delete
    @user = User.find_by_id(params[:id])
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    log_out
    flash[:success] = "Profile destroyed succesfully!"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end


    def authorized_user
      if !logged_in?
        flash[:error] = "ACCESS DENIED! PLEASE LOG IN!"
        redirect_to login_path

      elsif params[:id].to_i != current_user.id
        flash[:error] = "ACCESS DENIED! NO PERMITION TO ACCES THIS PROFILE"
        redirect_to root_path
      end
    end

    # def authorized_user
    #   unless params[:id] == current_user.id
    #     flash[:error] = "ACCESS DENIED! PLEASE LOG IN!"
    #     redirect_to login_path
    #   end
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
    reset_session
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def display_form_error(object, field)
    if object.errors[field].any?
      content_tag(:span, "", class: "fa fa-exclamation-circle fa-2x error-fa") +
      " " + content_tag(:span, object.errors[field].first.upcase)
    end
  end
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key, val| %>
    <% if key == "success" %>
      <div id="flash-container" class="<%= "flash-#{key}" %>">
        <p>
          <span class="fa fa-info-circle fa-2x"></span>
    <% elsif key == "error" %>
      <div id="flash-container" class="<%= "flash-#{key}" %>">
        <p>
          <span class="fa fa-exclamation-circle fa-2x"></span>
    <% end %>

          <%= val %>
        </p>
      </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row footer-center">
  <div class="col-md-10 col-md-offset-1">
    <nav id="footer">
      <ul>
        <li><%= link_to "HOME", root_path %></li>
        <% if !current_user %>
        <li><%= link_to "LOG IN", login_path %></li>
        <li><%= link_to "REGISTER", new_user_path %></li>
        <% else %>
        <li><%= link_to "PROFILE", user_path(current_user) %></li>
        <li><%= link_to "EDIT PROFILE",  edit_user_path(current_user) %></li>
        <li><%= link_to "DELETE", delete_user_path(current_user) %></li>
        <li><%= link_to "LOG OUT", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <div class="container" id="main">
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>

    <%#= console %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div class="fafix">
<p>
  <%= f.label :username, "USERNAME:" %>
  <%= display_form_error(f.object, :username) %>
</p>

  <i class="fa fa-user fa-fw fa-3x"></i>
  <%= f.text_field :username %>
</div>

<div class="fafix">
  <p>
    <%= f.label :email, "EMAIL:" %>
    <%# Displays first error for the field (see /helpers/users_helpers.rb ) %>
    <%= display_form_error(f.object, :email) %>
  </p>
  <i class="fa fa-envelope fa-fw fa-3x"></i>
  <%= f.email_field :email %>
</div>

<div class="fafix">
  <p>
    <%= f.label :password, "PASSWORD:" %>
    <%= display_form_error(f.object, :password) %>
  </p>
  <i class="fa fa-lock fa-fw fa-3x"></i>
  <%= f.password_field :password %>
</div>

<div class="fafix">
  <p>
    <%= f.label :password_confirmation, "PASSWORD CONFIRMATION:" %>
    <%= display_form_error(f.object, :password_confirmation) %>
  </p>
  <i class="fa fa-lock fa-fw fa-3x"></i>
  <%= f.password_field :password_confirmation %>
</div>

<%= f.button (submit_fa + submit_button).html_safe, type: "submit" %>

<% end %>

app/views/users/_user.html.erb
<%= user.id %>.
<%= user.username %> |
<%= link_to "Show", user_path(user) %> |
<%= link_to "Update", edit_user_path(user) %> |
<%= link_to "Delete", delete_user_path(user) %>
<br>

app/views/users/delete.html.erb
<pre>
██████╗ ███████╗██╗     ███████╗████████╗███████╗██╗
██╔══██╗██╔════╝██║     ██╔════╝╚══██╔══╝██╔════╝██║
██║  ██║█████╗  ██║     █████╗     ██║   █████╗  ██║
██║  ██║██╔══╝  ██║     ██╔══╝     ██║   ██╔══╝  ╚═╝
██████╔╝███████╗███████╗███████╗   ██║   ███████╗██╗
╚═════╝ ╚══════╝╚══════╝╚══════╝   ╚═╝   ╚══════╝╚═╝
</pre>

<p>
  AREY YOU SURE YOU WANT TO PERMANENTLY DELETE YOUR PROFILE?
</p>
<%= form_tag @user, method: :delete do %>
<%= button_tag ("<i class=\"fa fa-trash fa-2x\"></i> DELETE").html_safe, type: "submit" %>
<% end %>

app/views/users/edit.html.erb
<pre>
██╗   ██╗██████╗ ██████╗  █████╗ ████████╗███████╗██╗
██║   ██║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██║
██║   ██║██████╔╝██║  ██║███████║   ██║   █████╗  ██║
██║   ██║██╔═══╝ ██║  ██║██╔══██║   ██║   ██╔══╝  ╚═╝
╚██████╔╝██║     ██████╔╝██║  ██║   ██║   ███████╗██╗
 ╚═════╝ ╚═╝     ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝
</pre>


 <%= render partial: "form",
              locals: {
                submit_button: "UPDATE",
                submit_fa: "<i class=\"fa fa-wrench fa-2x\"></i> "
              }
  %>

app/views/users/index.html.erb
<pre>
██╗    ██╗███████╗██╗      ██████╗ ██████╗ ███╗   ███╗███████╗██╗
██║    ██║██╔════╝██║     ██╔════╝██╔═══██╗████╗ ████║██╔════╝██║
██║ █╗ ██║█████╗  ██║     ██║     ██║   ██║██╔████╔██║█████╗  ██║
██║███╗██║██╔══╝  ██║     ██║     ██║   ██║██║╚██╔╝██║██╔══╝  ╚═╝
╚███╔███╔╝███████╗███████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║███████╗██╗
 ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═
</pre>


<%= render @users %>

app/views/users/new.html.erb
<pre>
██████╗ ███████╗ ██████╗ ██╗███████╗████████╗███████╗██████╗ ██╗
██╔══██╗██╔════╝██╔════╝ ██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗██║
██████╔╝█████╗  ██║  ███╗██║███████╗   ██║   █████╗  ██████╔╝██║
██╔══██╗██╔══╝  ██║   ██║██║╚════██║   ██║   ██╔══╝  ██╔══██╗╚═╝
██║  ██║███████╗╚██████╔╝██║███████║   ██║   ███████╗██║  ██║██╗
</pre>


<%= render partial: "form",
            locals: {
              submit_button: "REGISTER",
              submit_fa: "<i class=\"fa fa-sign-in fa-2x\"></i> "
            }
%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <pre>
########################################
##...............??????...............##
##............??????????..............##
##...........????????????.............##
##..........???????????:???...........##
##.........????:::::::::???:..........##
##.........???::::::::::????..........##
##.........??::::::::::::???..........##
##.........??:::::::::::::?...........##
##.........??:::::::::::::?:..........##
##.........:?:::::::::::::?:..........##
##.........:::::::::::::::::..........##
##...........::::::::::::::...........##
##...........:::::::::::::............##
##............:::::::::::.............##
##.............:::::::::..............##
##............===:::::===.............##
##..........==::::::::::==............##
##........=====:::::::::====,.........##
##...============::::============.....##
##=================:================..##
##====================================##
########################################
########################################
  </pre>

</div>

<div class="col-md-8">

    <pre>
██████╗ ██████╗  ██████╗ ███████╗██╗██╗     ███████╗
██╔══██╗██╔══██╗██╔═══██╗██╔════╝██║██║     ██╔════╝
██████╔╝██████╔╝██║   ██║█████╗  ██║██║     █████╗
██╔═══╝ ██╔══██╗██║   ██║██╔══╝  ██║██║     ██╔══╝
██║     ██║  ██║╚██████╔╝██║     ██║███████╗███████╗
╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝
    </pre>

    <table class="profile-content">
      <tr>
        <td class="prfile-table-fa"> <span class="fa fa-user fa-wa fa-2x"></span></td>
        <td class="profile-table-label">USERNAME: </td>
        <td><%= @user.username %></td>
      </tr>
      <tr>
        <td class="table-fa"><span class="fa fa-envelope fa-wa fa-2x"></td>
        <td class="profile-table-label">EMAIL:</td>
        <td ><%= @user.email %></td>
      </tr>
      <tr>
        <td class="table-fa"><span class="fa fa-plus-circle fa-wa fa-2x"></span></td>
        <td class="profile-table-label">CREATED:</td>
        <td><%= @user.created_at %></td>
      </tr>
      <tr>
        <td class="table-fa"><span class="fa fa-wrench fa-wa fa-2x"></span></td>
        <td class="profile-table-label">UPDATED:</td>
        <td><%= @user.updated_at %></td>
      </tr>
    </table>



  </div>
</div>